// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: grabber/grabber.proto

package grabber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GrabRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	URL       string `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
}

func (x *GrabRequest) Reset() {
	*x = GrabRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grabber_grabber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrabRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabRequest) ProtoMessage() {}

func (x *GrabRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grabber_grabber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabRequest.ProtoReflect.Descriptor instead.
func (*GrabRequest) Descriptor() ([]byte, []int) {
	return file_grabber_grabber_proto_rawDescGZIP(), []int{0}
}

func (x *GrabRequest) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *GrabRequest) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type GrabResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestID string   `protobuf:"bytes,1,opt,name=RequestID,proto3" json:"RequestID,omitempty"`
	URLs      []string `protobuf:"bytes,2,rep,name=URLs,proto3" json:"URLs,omitempty"`
}

func (x *GrabResponse) Reset() {
	*x = GrabResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grabber_grabber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GrabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrabResponse) ProtoMessage() {}

func (x *GrabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grabber_grabber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrabResponse.ProtoReflect.Descriptor instead.
func (*GrabResponse) Descriptor() ([]byte, []int) {
	return file_grabber_grabber_proto_rawDescGZIP(), []int{1}
}

func (x *GrabResponse) GetRequestID() string {
	if x != nil {
		return x.RequestID
	}
	return ""
}

func (x *GrabResponse) GetURLs() []string {
	if x != nil {
		return x.URLs
	}
	return nil
}

var File_grabber_grabber_proto protoreflect.FileDescriptor

var file_grabber_grabber_proto_rawDesc = []byte{
	0x0a, 0x15, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72,
	0x22, 0x3d, 0x0a, 0x0b, 0x47, 0x72, 0x61, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x52, 0x4c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x52, 0x4c, 0x22,
	0x40, 0x0a, 0x0c, 0x47, 0x72, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x55, 0x52, 0x4c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x52, 0x4c,
	0x73, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x53, 0x70, 0x68, 0x65, 0x72, 0x69, 0x63, 0x61, 0x6c, 0x50, 0x6f, 0x74, 0x61, 0x74, 0x6f, 0x49,
	0x6e, 0x56, 0x61, 0x63, 0x75, 0x75, 0x6d, 0x2f, 0x73, 0x6f, 0x61, 0x2d, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x72, 0x61, 0x62, 0x62, 0x65, 0x72, 0x3b, 0x67, 0x72, 0x61,
	0x62, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grabber_grabber_proto_rawDescOnce sync.Once
	file_grabber_grabber_proto_rawDescData = file_grabber_grabber_proto_rawDesc
)

func file_grabber_grabber_proto_rawDescGZIP() []byte {
	file_grabber_grabber_proto_rawDescOnce.Do(func() {
		file_grabber_grabber_proto_rawDescData = protoimpl.X.CompressGZIP(file_grabber_grabber_proto_rawDescData)
	})
	return file_grabber_grabber_proto_rawDescData
}

var file_grabber_grabber_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_grabber_grabber_proto_goTypes = []interface{}{
	(*GrabRequest)(nil),  // 0: grabber.GrabRequest
	(*GrabResponse)(nil), // 1: grabber.GrabResponse
}
var file_grabber_grabber_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grabber_grabber_proto_init() }
func file_grabber_grabber_proto_init() {
	if File_grabber_grabber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grabber_grabber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrabRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grabber_grabber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GrabResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grabber_grabber_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grabber_grabber_proto_goTypes,
		DependencyIndexes: file_grabber_grabber_proto_depIdxs,
		MessageInfos:      file_grabber_grabber_proto_msgTypes,
	}.Build()
	File_grabber_grabber_proto = out.File
	file_grabber_grabber_proto_rawDesc = nil
	file_grabber_grabber_proto_goTypes = nil
	file_grabber_grabber_proto_depIdxs = nil
}
